version: '3'

services:
  rabbitmq.consumer:
    image: rabbitmq.consumer:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitmq.consumer$
    volumes:
      - D:\Docker test\RabbitMQ.Consumer\RabbitMQ.Consumer:/app
      - C:\Users\Shoieb\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_rabbitmq.consumer$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitmq.consumer$ bin/Debug/netcoreapp2.0/RabbitMQ.Consumer.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
